/*
 * generated by Xtext
 */
package co.edu.unal.G.ui.contentassist

import co.edu.unal.G.ui.contentassist.AbstractGDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GDslProposalProvider extends AbstractGDslProposalProvider {
}
