/*
 * generated by Xtext
 */
package co.edu.unal.A.ui.contentassist

import co.edu.unal.A.ui.contentassist.AbstractADslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ADslProposalProvider extends AbstractADslProposalProvider {
}
