/*
 * generated by Xtext
 */
package co.edu.unal.F;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FDslRuntimeModule extends co.edu.unal.F.AbstractFDslRuntimeModule {

}
