/*
* generated by Xtext
*/
package co.edu.unal.F;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FDslStandaloneSetup extends FDslStandaloneSetupGenerated{

	public static void doSetup() {
		new FDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

