/*
 * generated by Xtext
 */
package co.edu.unal.D.ui.contentassist

import co.edu.unal.D.ui.contentassist.AbstractDDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DDslProposalProvider extends AbstractDDslProposalProvider {
}
