/*
 * generated by Xtext
 */
package co.edu.unal.C.ui.contentassist

import co.edu.unal.C.ui.contentassist.AbstractCDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CDslProposalProvider extends AbstractCDslProposalProvider {
}
