/*
* generated by Xtext
*/
package co.edu.unal.D;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DDslStandaloneSetup extends DDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

