/*
 * generated by Xtext
 */
package co.edu.unal.D;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DDslRuntimeModule extends co.edu.unal.D.AbstractDDslRuntimeModule {

}
