/*
 * generated by Xtext
 */
package co.edu.unal.B.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BDslUiModule extends co.edu.unal.B.ui.AbstractBDslUiModule {
	public BDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
