/*
 * generated by Xtext
 */
package co.edu.unal.C.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CDslUiModule extends co.edu.unal.C.ui.AbstractCDslUiModule {
	public CDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
