/*
 * generated by Xtext
 */
package co.edu.unal.D.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DDslUiModule extends co.edu.unal.D.ui.AbstractDDslUiModule {
	public DDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
