/*
 * generated by Xtext
 */
package co.edu.unal.E.ui.contentassist

import co.edu.unal.E.ui.contentassist.AbstractEDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EDslProposalProvider extends AbstractEDslProposalProvider {
}
