/*
 * generated by Xtext
 */
package co.edu.unal.A;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ADslRuntimeModule extends co.edu.unal.A.AbstractADslRuntimeModule {

}
