/*
 * generated by Xtext
 */
package co.edu.unal.A.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ADslUiModule extends co.edu.unal.A.ui.AbstractADslUiModule {
	public ADslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
