/*
 * generated by Xtext
 */
package co.edu.unal.G.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GDslUiModule extends co.edu.unal.G.ui.AbstractGDslUiModule {
	public GDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
