/*
 * generated by Xtext
 */
package co.edu.unal.F.ui.contentassist

import co.edu.unal.F.ui.contentassist.AbstractFDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FDslProposalProvider extends AbstractFDslProposalProvider {
}
