/*
 * generated by Xtext
 */
package co.edu.unal.C;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CDslRuntimeModule extends co.edu.unal.C.AbstractCDslRuntimeModule {

}
