/*
 * generated by Xtext
 */
package co.edu.unal.B;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDslRuntimeModule extends co.edu.unal.B.AbstractBDslRuntimeModule {

}
