/*
* generated by Xtext
*/
package co.edu.unal.B;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BDslStandaloneSetup extends BDslStandaloneSetupGenerated{

	public static void doSetup() {
		new BDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

