/*
 * generated by Xtext
 */
package co.edu.unal.E.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EDslUiModule extends co.edu.unal.E.ui.AbstractEDslUiModule {
	public EDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
