/*
 * generated by Xtext
 */
package co.edu.unal.E;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EDslRuntimeModule extends co.edu.unal.E.AbstractEDslRuntimeModule {

}
