/*
* generated by Xtext
*/
package co.edu.unal.E;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EDslStandaloneSetup extends EDslStandaloneSetupGenerated{

	public static void doSetup() {
		new EDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

