/*
 * generated by Xtext
 */
package co.edu.unal.F.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FDslUiModule extends co.edu.unal.F.ui.AbstractFDslUiModule {
	public FDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
