/*
 * generated by Xtext
 */
package co.edu.unal.G;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GDslRuntimeModule extends co.edu.unal.G.AbstractGDslRuntimeModule {

}
