/*
 * generated by Xtext
 */
package co.edu.unal.B.ui.contentassist

import co.edu.unal.B.ui.contentassist.AbstractBDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BDslProposalProvider extends AbstractBDslProposalProvider {
}
